### ISSUE TITLE
Plugin not installable due to missing file

### ISSUE THREAD

**Issue by alve89** [gkralik/hikashop-payment-sofort#1]
Hey Gregor,

I'm getting this error message while trying to install this extension:
>JInstaller: :Install: Die Datei „`tmp/install_598caba084348/hikashop-payment-sofort-1.1.0/library/sofort.php“ existiert nicht.

Why isn't this file within the archive?

Many thanks in advance and best regards!

**Comment by gkralik** [comment]
The tag 1.1.0 had a wrong plugin descriptor file, which included `library/sofort.php` although it is not needed.
Fixed in 1.1.1 or master.
